services:
  word-cloud-bot:
    build: .
    command: gunicorn --workers=2 main:flask_app -b 0.0.0.0:3002
    volumes:
        - .:/code
    ports:
        - 3002:3002
    restart: "unless-stopped"
    depends_on:
        - db
  db:
    image: "postgres:14.2"
    restart: "unless-stopped"
    container_name: "word-cloud-db"
    expose:
      - 5432
    volumes:
            - word_cloud_postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: "slackapp"
volumes:
  word_cloud_postgres_data:
