services:
  word-cloud-bot:
    build: .
    command: python3 main.py
    volumes:
        - .:/code
    ports:
        - 3002:3002
    restart: "unless-stopped"
    depends_on:
        - db
  db:
    image: "postgres:14.2"
    restart: "unless-stopped"
    container_name: "word-cloud-db"
    expose:
      - 5432
    volumes:
            - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "slack-bot"
volumes:
  postgres_data:
